
branches:
  only:
    - master

language: objective-c

env:
   - TEST_DIR=HelloMap.Objective-C

script: cd $TEST_DIR && xcodebuild -workspace $TEST_DIR.xcworkspace -scheme $TEST_DIR -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO