
branches:
  only:
    - master

language: objective-c

env:
   - TEST_DIR=hellomap-cocoapods

script: cd $TEST_DIR && pod install && xcodebuild -workspace $TEST_DIR.xcworkspace -scheme $TEST_DIR -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO